@host = localhost:3000
@path = /company/queue

### Deactivate

PUT http://{{host}}{{path}}?queue_id=QUEUE12345 HTTP/1.1
Content-Type: application/json

{
    "status": "DEACTIVATE"
}

### Activate

PUT http://{{host}}{{path}}?queue_id=QUEUE12345 HTTP/1.1
Content-Type: application/json

{
    "status": "ACTIVATE"
}

### Unknown Queue Number

PUT http://{{host}}{{path}}?queue_id=QUEUE12346 HTTP/1.1
Content-Type: application/json

{
    "status": "ACTIVATE"
}

### Invalide status

PUT http://{{host}}{{path}}?queue_id=QUEUE12345 HTTP/1.1
Content-Type: application/json

{
    "status": "ACTI VATE"
}